version: '3.9'
services:
  nest:
    build: . 
    #image: node:14.17.5-alpine
    #stdin_open: true
    #tty: true
    entrypoint: ./node_modules/.bin/ng serve --host 0.0.0.0
   
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app
